Fix broken pipe: consume POST body (#2887)
Attempts to fix flakiness of our tests:

```
    error: error sending request for url (http://127.0.0.1:45915/api/v1/packages/new)

    Caused by:
        0: client error (SendRequest)
        1: error writing a body to connection
        2: Broken pipe (os error 32)
```

The theory is that response is being returned prior to POST request body
being consumed, thus resulting in `error writing a body to connection`